### ISSUE TITLE
Error: load pubkey "xxxx": invalid format

### ISSUE THREAD

**Issue by pmkrawczyk** [google-github-actions/ssh-compute#18]
Hi,

I'm trying to use ssh-compute to execute a test command on a VM. I generated SSH key pair using [these instructions](https://cloud.google.com/compute/docs/connect/create-ssh-keys#linux-and-macos), added the private key to GitHub secrets, and public key to instace meta.

This is the job I'm running:

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'XXXXXXX'
          service_account: 'XXXXXXXX'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'XXXXXXXX'
          zone: 'XXXXXXXX'
          ssh_private_key: '${{ secrets.XXXXXXXXX }}'
          command: 'echo Hello world'

      # Example of using the output
      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'` 

The command fails like this: 

``google-github-actions/ssh-compute failed with: failed to execute gcloud command `gcloud compute ssh xxxxxxx --zone xxxxxx --ssh-key-file /tmp/802bd75634c5a963bee50731/google_compute_engine --quiet --tunnel-through-iap --command echo Hello world`: load pubkey "/tmp/802bd75634c5a963bee50731/google_compute_engine": invalid format``

I tried different key pairs, to no avail. The keys work in a regular SSH session.

Could you please point me towards a solution? 

Thanks!

**Comment by FrodoTheTrue** [comment]
Hi @pmkrawczyk! Thanks for raising the issue.

Could you please try to exec the command locally (using gcloud cli) and generated public and private keys?

```
gcloud compute ssh xxxxxxx --zone xxxxxx --ssh-key-file /path --tunnel-through-iap
```

Does it work as expected?

**Comment by pmkrawczyk** [comment]
Hi, yes, locally it works fine!

**Comment by shengLin-alex** [comment]
same problem occur, set ssh_keys_dir still not work.

**Comment by ninja-ops** [comment]
running into the same issue ..

the metadata of the instance will contain a key starting with "-----BEGIN PUBLIC KEY-----" .. seems to be an issue with generating the pubkey in the wrong format .. this metadata will occure in the instance and needs to be cleaned by hand ..

**Comment by ninja-ops** [comment]
workaround ..

if you extract the public key from the json of the service account ..

    cat key.json | jq -r .private_key > key.txt
    chmod 600 key.txt
    ssh-keygen -f key.txt -y > pub.txt

and place the content of pub.txt directly to the compute instance as additional ssh-key (dont forget the user runner as third element)

   ssh-rsa jdfgkshfdjktz34789584789358943 runner

then the private key works, who is defined in the action, since the error pubkey generating is only a warning ..

in addtion to this the faulty pubkey is added, but since we defined a working pubkey by hand, the login works as expected ..

**Comment by FrodoTheTrue** [comment]
Should be fixed now here: https://github.com/google-github-actions/ssh-compute/pull/20
Public key generates in the correct format.
